### PR TITLE
GenWeight Parsing

### PR DESCRIPTION
**Pull request by dteague**
# Overview
This PR is adding the parsing of GEN weights, ie extending the LHEWeight reading to GenWeight. 

# Details
The Gen weights are not stored as xml, but the format is parsed and sanitized before being inserted into the weightVector, so the code can be reused. Because of this, the first commit is moving the weightVector building to teh `WeightHelper` class so it is accessible to `GenWeightHelper`. 

The Second commit is to handle the act GenWeight parsing. Currently the code only sensible handles the LHE weights and the others are included, but not in a very intelligent way. This can be remedied with future commits, but this should be fairly simple.

### CODE REVIEW

**Comment by kdlong** [comment]
Thanks! Will take a closer look later today or tomorrow. In the meantime it would be good to check whether this works with the Nano implementation (a quick check I didn't see the weights making it in)

One other quick thing: did you run clang-format? I see some formatting changes showing up in the git diff, but maybe they were just left over from before.

**Comment by dteague** [comment]
No to the formatting... I'll do some tests and cleanup my commits after I get everything working!

**Comment by dteague** [comment]
Ran over the susyweight file and it seems to read it without a hitch and the print out of the weights seems reasonable. This still needs to be checked that the weights are being actually filled correctly, but the parsing and setting up of the weights themselves seems to work fine, at least to my knowledge.

I also fixed the formatting issue

**Comment by kdlong** [comment]
It looks good to me. I have been testing and I found a few issues (most not introduced here) that I'll address in a PR shortly.

**Pull request merged**
